#
#Maximum amount of items one slot of a plate can hold. 
#Does not override item's max stack size.
# Default: 16
#Range: 1 ~ 64
maxPlateStackSize = 16
#
#If set to true, allow player to keep eating off the plate, even if they're not hungry. 
#Food buffs/debuffs are still applied.
#Default: false
allowOvereating = false
#
#If true, only food items & items inside "dinnerware:additional_food" tag are allowed to be placed on plates. 
#Otherwise, anything will fit. Your rendering mileage may vary. 
#Default: true
onlyFoodOnPlate = true
#
#A list of items to forbid from being eaten, even if they're part of "dinnerware:additional_food" tag. 
#Items listed here may still be placed on a plate. 
#Default: ["artifacts:everlasting_beef", "artifacts:eternal_steak"]
foodBlacklist = ["artifacts:everlasting_beef", "artifacts:eternal_steak"]
#
#If set to true, plates become fragile, i.e. break under various circumstances. 
#Like walking on them. 
#Entities inside "fragile_plate_ignored" tag are ignored. 
#Default: false
fragilePlates = false
#
#If set to true, the bottom right slot becomes the main one. 
#The plate is basically gets mirrored. 
#Be careful when changing this with already existing plates in the world. 
#Default: false
rightToLeft = false
#
#The mode in which the food will be eaten off of a plate. 
# QUEUE:       all the food is eaten in the Main dish slot first, then in Side dish slot, then in Extra dish slot; 
# ROUND_ROBIN: each new right-click will take the food from the new slot. Clicks with no food eaten still count; 
# AIMING:      the food is eaten depending on where and crosshair is aimed at the time of right-click; 
#Default: AIMING
#Allowed Values: QUEUE, ROUND_ROBIN, AIMING
eatingMode = "AIMING"
#
#If set to true, the tray will behave like a bundle: 
#If there's a matching plates stack, the picked up one will be merged into it. 
#Otherwise, the merging only happens for the topmost plate. 
#Default: false
trayMergeMatchingItem = false

