volume = 1.0
maxPlayCont = 8
spatial = true
sampleRate = 44100
useYoutubeDownloader = true
hideDisplaySprite = false
hideDecorativeAntenna = false
ConnectionTimeout = 10000
ReadTimeout = 30000
DownloadRetryCount = 3
DownloadRetryDelayMS = 1000
relayServerURL = "https://raw.githubusercontent.com/TeamFelnull/IamMusicPlayer/master/relay_server.json"
lavaPlayerNativesURL = "https://raw.githubusercontent.com/Mod-Sauce/lavanatives/refs/heads/main/lavaplayer/natives_link.json"
hashBaseUrl = "https://raw.githubusercontent.com/Mod-Sauce/lavanatives/refs/heads/main/lavaplayer"
IMPRFolder = "iammusicplayerrenewed"
lavaNativesFolder = "lavaplayer_natives"
maxWaitTime = 10000
retryTime = 3000
dropItemRing = true
showMusicLines = false
showSpeakerRange = false
soundPhysicsRemasteredIntegration = true
configVersion = "3"
